### PR TITLE
Add items filtering to the options

### LINKED ISSUE #9: Feature - Option to filter feeds by property (like published: true/false)

### PR DESCRIPTION
**Pull request by noreaum**
Fixes #9 

Add a `filterItems` option to filter item using a function.

### CODE REVIEW

**Comment by Edmund1645** [comment]
I really needed this feature. thanks!

**Comment by rasulkireev** [comment]
@darthmeme Can we please get this approved?

Thanks a ton in advance.

**Comment by maciejwalkowiak** [comment]
@darthmeme could you please merge this one?

**Comment by darthmeme** [comment]
Apologies for the *extremely* long wait. `v1.3.0` has been published with these changes.

**Comment by maciejwalkowiak** [comment]
Fantastic! Thanks @darthmeme

**Pull request merged**
